### ISSUE TITLE
test-osuosl-aix61-ppc64_be-3 taken offline

### ISSUE THREAD

**Issue by Trott** [nodejs/build#1893]
I took test-osuosl-aix61-ppc64_be-3 offline for repeated build failures. Didn't investigate too closely but thought "Hmmm....out of disk space maybe?"

@nodejs/platform-aix

**Comment by miladfarca** [comment]
Can I please have my public key added to this machine? I already have approvals in this ticket: https://github.com/nodejs/build/issues/1706
```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDQZihjEXcY52UZo09CEb29HwOWwXcmwbwZFR4rsACQQyGUexL4fkVrFfwuG8eV1vg5KECsO8LiGY/MHkNIpABaJJoip0Qxgv0pAFtAukIDjLXXOV/VNJjfIto16vOAehRZkmI+BtQP8TjoT2CSyJgvVQcay8BhH52in1LQQsyCi2crHLYzDrrCgY/rAmuVb1MzMnT8mFOdJ8E5RBhjnmc1K4YBKmNTf6yefgbOJssI0lLzp7Q2uytzp3pipg7AO/VqmRn8953UTJS/cOQeBi3nCYGpz4I7kOKHgwbdW1IP/XFfm0KO5daulHQeToRGIE85ntxF314wsYE3ZyeJwKgH
```

**Comment by Trott** [comment]
> ```
> ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDQZihjEXcY52UZo09CEb29HwOWwXcmwbwZFR4rsACQQyGUexL4fkVrFfwuG8eV1vg5KECsO8LiGY/MHkNIpABaJJoip0Qxgv0pAFtAukIDjLXXOV/VNJjfIto16vOAehRZkmI+BtQP8TjoT2CSyJgvVQcay8BhH52in1LQQsyCi2crHLYzDrrCgY/rAmuVb1MzMnT8mFOdJ8E5RBhjnmc1K4YBKmNTf6yefgbOJssI0lLzp7Q2uytzp3pipg7AO/VqmRn8953UTJS/cOQeBi3nCYGpz4I7kOKHgwbdW1IP/XFfm0KO5daulHQeToRGIE85ntxF314wsYE3ZyeJwKgH
> ```

Done.

**Comment by miladfarca** [comment]
@mhdawson As mentioned, issue might be disk space related. `ppc64_be-3` has both `/home/iojs` and `/home/iojs/build` on the same ~9 GB disk (and is running out) whereas `ppc64_be-2` has `/home/iojs/` on a 55 GB disk and `/home/iojs/build` on a separate 10 GB disk.
here is the `df` output on `-3` under `home/iojs/`:
```
3.66    ././.ccache
1.75    ././build
0.83    ././gcc-6.3.0-1
```

**Comment by mhdawson** [comment]
I'm not sure the disks are different, but the sizes of the disks are.  Either we expanded home manually and missed adding that to the manual setup instructions or the vm came with different sizes to start.

I ran `chfs -a size=+2000000 /home`

which I think I got wrong since it expanded more than I expected as /home now shows as 101G. In any case that should be big enough now.

@sam-github can you review and update the manual instructions to so that we check that the /home size is at least 55G and to expand if it is not that big using the appropriate command.

**Comment by mhdawson** [comment]
/home is now only 23% so I think we can re-able:

```
ash-4.3# df -k
Filesystem    1024-blocks      Free %Used    Iused %Iused Mounted on
/dev/hd4          2490368    559748   78%    21819    15% /
/dev/hd2          2752512    460176   84%    47532    31% /usr
/dev/hd9var        589824    157652   74%     9142    20% /var
/dev/hd3          3145728   2475300   22%     8516     2% /tmp
/dev/hd1         10158080   2005356   81%   259081    23% /home
/dev/hd11admin      131072    130692    1%        3     1% /admin
/proc                   -         -    -         -     -  /proc
/dev/hd10opt      1114112    273976   76%    27325    31% /opt
/dev/livedump      262144    261776    1%        4     1% /var/adm/ras/livedump
/aha                    -         -    -        87     1% /aha
```

**Comment by mhdawson** [comment]
@Trott re-enabled, thanks for creating the issue to let us know there was an issue.  If builds still fail on this machine please let us know.

**Comment by mhdawson** [comment]
Still seeing failures today, disabled again.  @miladfarca can you take another look.

**Comment by mhdawson** [comment]
ok turns out I did not actually increase the size.  I can't get it quite as big as the other machines but upped to 29G which is 3x what it was before.  Hopefully that will be enough.

**Comment by mhdawson** [comment]
Reenabling.

**Comment by Trott** [comment]
Taking offline again. Failing almost every time with stuff like this:

```console
10:09:50 Build timed out (after 10 minutes). Marking the build as failed.
10:11:51 g++: internal compiler error: Terminated (program collect2)
10:11:51 Please submit a full bug report,
10:11:51 with preprocessed source if appropriate.
10:11:51 See <http://gcc.gnu.org/bugs.html> for instructions.
10:11:51 gmake[2]: *** [/home/iojs/build/workspace/node-test-commit-aix/nodes/aix61-ppc64/out/Release/mkcodecache] Error 4
10:11:51 gmake[2]: *** Waiting for unfinished jobs....
10:11:51 collect2: fatal error: ld terminated with signal 15 [Terminated]
10:11:51 compilation terminated.
10:11:51 gmake[2]: *** [/home/iojs/build/workspace/node-test-commit-aix/nodes/aix61-ppc64/out/Release/node_mksnapshot] Terminated
10:11:51 collect2: fatal error: ld terminated with signal 15 [Terminated]
10:11:51 compilation terminated.
10:12:07 Build was aborted
10:12:07 Performing Post build task...
10:12:07 Match found for : : True
10:12:07 Logical operation result is TRUE
```

**Comment by miladfarca** [comment]
Is it possible to remove any cache or clean the workspace? I do these these errors from time to time on AIX when a previous compilation gets interrupted. Removing the files and starting a fresh build usually works.

**Comment by Trott** [comment]
> Is it possible to remove any cache or clean the workspace? I do these these errors from time to time on AIX when a previous compilation gets interrupted. Removing the object files and starting a fresh build usually works.

Sure, I can clear the workspace and put it back online to see what happens...

**Comment by Trott** [comment]
Actually, seems like there's a lot of surprising cruft in the workspace... Files that look like `ccS8JucI.ld` and `cccb27Jh.ld` lying around where they would seem to have no business being, for example. Anyway, all cleaned up and back online....(`rm -r` is strangely slow on these machines--I wonder if AIX does some sort of special zero'ing out of the disk or something?)

**Comment by Trott** [comment]
OK, after deleting the workspaces, stuff is passing again. Closing. Thanks, @miladfarca!

**Comment by mhdawson** [comment]
Still seems to have issues, re-opening

**Comment by miladfarca** [comment]
I manually fetched and compiled node master on `ppc64_be-3` successfully. It seems to be taking longer than usual, that's why (Jenkins?) just kills the process in the final stages of linking. 

I did the final linking step (right before it timesout) manually, it took about `1 min 50 sec`. Tested the same step on `ppc64_be-2` which took `2 min and 10 sec`. It could be that a multi threaded compile is exhausting `ppc64_be-3` resources on the final link stages making it slower. 

I noticed running `df` on `ppc64_be-2` shows mounted `ramdisks` which don't exist on `ppc64_be-3`:
```
...
/dev/ramdisk0   10000000   9699344    4%        5     1% /ramdisk0
/dev/ramdisk1   23000000  14937472   36%   152622     8% /home/iojs/build
```
@sam-github Michael mentioned this machine has had ramdisk issues in the past. Rebooting  and reconfiguring ramdisk might be helpful.

**Comment by sam-github** [comment]
Rebooting is not recommended, I did not do that.

I redid the manual setup from https://github.com/nodejs/build/blob/master/setup/aix61/manualBootstrap.md#setup-ramdisks
and re-enabled.

I'll up the priority of the TODO item to write an rc script that does the ramdisk setup on boot.

**Comment by sam-github** [comment]
https://ci.nodejs.org/computer/test-osuosl-aix61-ppc64_be-3/builds

CI is green again.
