### ISSUE TITLE
Windows release builds stuck

### ISSUE THREAD

**Issue by richardlau** [nodejs/build#3477]
Looks like we have executor starvation for the [vs2019-arm64](https://ci-release.nodejs.org/label/vs2019-arm64) machines on ci-release. The three current non-disconnected nodes look stuck:
- https://ci-release.nodejs.org/job/iojs+release/nodes=vs2019-arm64/9599/ (running for a day)
- https://ci-release.nodejs.org/job/iojs+release/nodes=vs2019-arm64/9595/ (running for three days)
- https://ci-release.nodejs.org/job/iojs+release/nodes=vs2019-arm64/9585/ (running for seven days)

All three appear to be attempting to download the x64 node binary to run license2rtf:
e.g. https://ci-release.nodejs.org/job/iojs+release/nodes=vs2019-arm64/9599/console
```console
13:16:23 Cross-compilation to ARM64 detected. We'll use the x64 Node executable for license2rtf.
13:16:23 Downloading x64 node.exe...
```

Since this tries to [download from https://nodejs.org/dist](https://github.com/nodejs/node/blob/fcf5de008a59229fe65a7b8e4e45fb4cfef4de81/vcbuild.bat#L394) this is probably related to the slow downloads/500 errors due to the server that hosts the downloads being overwhelmed.

I haven't canceled any of the stuck jobs in case somebody wants to investigate further.

cc @StefanStojanovic

**Comment by StefanStojanovic** [comment]
I've taken care of it. It was indeed a problem with downloading x64 node.exe for signing. On test CI we have a caching mechanism to ensure things like this do not happen. The same thing, or something similar, should be made on the release CI as well in the future. This is fixed for now.

**Comment by targos** [comment]
It still happens occasionally:
https://ci-release.nodejs.org/job/iojs+release/10569/nodes=vs2022-arm64/
https://ci-release.nodejs.org/job/iojs+release/10559/nodes=vs2022-arm64/

**Comment by targos** [comment]
https://ci-release.nodejs.org/job/iojs+release/10581/nodes=vs2022-arm64/

**Comment by StefanStojanovic** [comment]
This issue hasn't reappeared in over a week, plus from the logs, I see that the new mechanism is working as expected, so downloads are no longer happening. Closing this issue, and will apply this to the Test CI in the near future.
